import collections
from typing import Any, NamedTuple, final, Sequence

NOP: int
APPEND: int
INVALIDATE: int
LOCAL_ONLY: int
RUNTIME_ONLY: int
SYSTEM: int
SYSTEM_ONLY: int
CURRENT_USER: int
OS_ROOT: int

class _Reader:
    def __init__(
        self,
        flags: int | None = None,
        path: int | str | bytes | None = None,
        files: Sequence[str] | Sequence[int] | None = None,
        namespace: str | bytes | None = None,
    ) -> None: ...
    def fileno(self, /) -> int | None: ...
    def reliable_fd(self, /) -> bool: ...
    def get_events(self, /) -> int | None: ...
    def get_timeout(self, /) -> int | None: ...
    def get_timeout_ms(self, /) -> int | None: ...
    def close(self, /) -> None: ...
    def get_usage(self, /) -> int: ...
    def __enter__(self, /) -> "_Reader": ...
    def __exit__(self, /) -> None: ...
    def _next(self, skip: int | None, /) -> bool: ...
    def previous(self, skip: int | None, /) -> bool: ...
    def get(self, field: str, /) -> str: ...
    def _get_all(self, /) -> dict[str, str]: ...
    def _get_realtime(self, /) -> int: ...
    def _get_monotonic(self, /) -> tuple[int, bytes]: ...
    def add_match(self, match: str | bytes, /) -> None: ...
    def add_disjunction(self, /) -> None: ...
    def add_conjunction(self, /) -> None: ...
    def flush_matches(self, /) -> None: ...
    def seek_head(self, /) -> None: ...
    def seek_tail(self, /) -> None: ...
    def seek_realtime(self, timestamp: int, /) -> None: ...
    def seek_monotonic(self, timestamp: int, bootid: str | None, /) -> None: ...
    def _get_start(self, /) -> int: ...
    def _get_end(self, /) -> int: ...
    def process(self, /) -> int: ...
    def wait(self, timeout: int | None = None, /) -> int: ...
    def seek_cursor(self, cursor: str, /) -> None: ...
    def _get_cursor(self, /) -> str: ...
    def test_cursor(self, cursor: str, /) -> bool: ...
    def query_unique(self, field: str, /) -> set[str]: ...
    def enumarate_fields(self, /) -> set[str]: ...
    def has_runtime_files(self, /) -> bool: ...
    def has_persistent_files(self, /) -> bool: ...
    def get_catalog(self, /) -> bool: ...
    def get_data_threshold(self, /) -> int: ...
    def set_data_threshold(self, treshold: int, /) -> None: ...

def _get_catalog(id: str | None, /) -> str: ...

from _typeshed import structseq

@final
class Monotonic(structseq, tuple[str, str]):
    @property
    def timestamp(self) -> str: ...
    @property
    def bootid(self) -> str: ...
