# SPDX-License-Identifier: LGPL-2.1-or-later

from types import TracebackType as _TracebackType
from typing import final as _final, Sequence as _Sequence
from _typeshed import structseq as _structseq

__version__: str

NOP: int
APPEND: int
INVALIDATE: int
LOCAL_ONLY: int
RUNTIME_ONLY: int
SYSTEM: int
SYSTEM_ONLY: int
CURRENT_USER: int
OS_ROOT: int

class _Reader:
    def __init__(
        self,
        flags: int | None = None,
        path: int | str | bytes | None = None,
        files: _Sequence[str] | _Sequence[int] | None = None,
        namespace: str | bytes | None = None,
    ) -> None: ...
    def fileno(self, /) -> int | None: ...
    def reliable_fd(self, /) -> bool: ...
    def get_events(self, /) -> int | None: ...
    def get_timeout(self, /) -> int | None: ...
    def get_timeout_ms(self, /) -> int | None: ...
    def close(self, /) -> None: ...
    def get_usage(self, /) -> int: ...
    def _next(self, skip: int | None, /) -> bool: ...
    def previous(self, skip: int | None, /) -> bool: ...
    def _get(self, field: str, /) -> str: ...
    def _get_all(self, /) -> dict[str, str]: ...
    def _get_realtime(self, /) -> int: ...
    def _get_monotonic(self, /) -> tuple[int, bytes]: ...
    def add_match(self, match: str | bytes, /) -> None: ...
    def add_disjunction(self, /) -> None: ...
    def add_conjunction(self, /) -> None: ...
    def flush_matches(self, /) -> None: ...
    def seek_head(self, /) -> None: ...
    def seek_tail(self, /) -> None: ...
    def seek_realtime(self, timestamp: int, /) -> None: ...
    def seek_monotonic(self, timestamp: int, bootid: str | None, /) -> None: ...
    def _get_start(self, /) -> int: ...
    def _get_end(self, /) -> int: ...
    def process(self, /) -> int: ...
    def wait(self, timeout: int | None = None, /) -> int: ...
    def seek_cursor(self, cursor: str, /) -> None: ...
    def _get_cursor(self, /) -> str: ...
    def test_cursor(self, cursor: str, /) -> bool: ...
    def query_unique(self, field: str, /) -> set[str]: ...
    def enumerate_fields(self, /) -> set[str]: ...
    def has_runtime_files(self, /) -> bool: ...
    def has_persistent_files(self, /) -> bool: ...
    def get_catalog(self, /) -> bool: ...
    def __enter__(self, /) -> "_Reader": ...
    def __exit__(
        self,
        type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: _TracebackType | None) -> bool: ...

    @property
    def data_threshold(self, /) -> int: ...

    @data_threshold.setter
    def data_threshold(self, treshold: int, /) -> None: ...

    @property
    def closed(self, /) -> bool: ...

def _get_catalog(id: str | None, /) -> str: ...


@_final
class Monotonic(_structseq, tuple[str, str]):
    @property
    def timestamp(self) -> str: ...
    @property
    def bootid(self) -> str: ...
