__versions__: str

def seats() -> list[str]: ...
def sessions() -> list[str]: ...
def machine_names() -> list[str]: ...
def uids() -> list[int]: ...

class Monitor:
    def __init__(self, category: str | None = None) -> None: ...
    
    def fileno(self) -> int: ...
    def get_events(self) -> int: ...
    def get_timeout(self) -> int | None: ...
    def get_timeout_ms(self) -> int: ...
    def close(self) -> None: ...
    def flush(self) -> None: ...
    def __enter__(self) -> "Monitor": ...
    def __exit__(self) -> None: ...
